<a href="https://colab.research.google.com/github/Manju1803-a11y/NA_assignment/blob/main/DemoNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
a1=np.array([4,6,7,8,9])
print(a1)

[4 6 7 8 9]


In [ ]:
a2=np.arange(1,30)

In [ ]:
print(a2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


In [ ]:
a3=np.arange(10,30,3)
print(a3)

[10 13 16 19 22 25 28]


In [ ]:
a1=np.array([4,6,7,8,9])
a2=np.arange(1,10)

In [ ]:
print(a1)
print(a2)

[4 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
id(a1)

137211819646128

In [ ]:
id(a2)

137211833622256

In [ ]:
a1=a2
print(a1)
id(a1)

[1 2 3 4 5 6 7 8 9]


137211833622256

In [ ]:
id(a1)
#id(a2)
#a3=np.copy(a1)

137211833622256

In [ ]:
a2=np.copy(a1)
print(a2)

[1 2 3 4 5 6 7 8 9]


In [ ]:
id(a2)

137211821145520

tuples


In [ ]:
a4=np.array({'one':1,
              'two':2,
             'three':3,
             'four':4})
print(a4)


{'one': 1, 'two': 2, 'three': 3, 'four': 4}


In [ ]:
a1=np.array([4,6,7,8,9])
len(a1)

5

In [ ]:
a1.size

5

In [ ]:
a1.ndim

1

In [ ]:
a2=np.array([11,20.4,False])
a2

array([11. , 20.4,  0. ])

In [ ]:
a2=np.array([11,20.4,True])
a2

array([11. , 20.4,  1. ])

linspace

In [ ]:
np.linspace(10,-10,10)

array([ 10.        ,   7.77777778,   5.55555556,   3.33333333,
         1.11111111,  -1.11111111,  -3.33333333,  -5.55555556,
        -7.77777778, -10.        ])

In [ ]:
np.linspace(10,200, 30)

array([ 10.        ,  16.55172414,  23.10344828,  29.65517241,
        36.20689655,  42.75862069,  49.31034483,  55.86206897,
        62.4137931 ,  68.96551724,  75.51724138,  82.06896552,
        88.62068966,  95.17241379, 101.72413793, 108.27586207,
       114.82758621, 121.37931034, 127.93103448, 134.48275862,
       141.03448276, 147.5862069 , 154.13793103, 160.68965517,
       167.24137931, 173.79310345, 180.34482759, 186.89655172,
       193.44827586, 200.        ])

In [ ]:
np.zeros(30)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
d2=np.array([[1,2,3],[5,6,7]])
d2
d2.ndim

2

In [ ]:
d3=np.array([[2,3,4],[7,8,9],[9,8,5]])
d3


array([[2, 3, 4],
       [7, 8, 9],
       [9, 8, 5]])

In [ ]:
d3.ndim

2

In [ ]:
np.ones((35,35))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [ ]:
np.zeros((35,35))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
a4=np.zeros((3,3))

In [ ]:
a4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a4[[0][0]]

array([0., 0., 0.])

In [ ]:
a4[0]

array([0., 0., 0.])

properties
* shape
*size
*ndim

In [ ]:
a5=np.arange(12)
a5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a5.size

12

In [ ]:
a5.shape

(12,)

In [ ]:
a5.ndim

1

In [ ]:
a5.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

create a numpy array of size 24,reshape to 4 different shapes

In [ ]:
a6=np.arange(24)
a6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a6.size

24

In [ ]:
a6.shape

(24,)

In [ ]:
a6.ndim

1

In [ ]:
a6.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a6.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a6.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a6.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [ ]:
a6.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

randoms

In [ ]:
e1=np.random.randn(3,4)
e1

array([[-1.34326319,  0.10979964,  0.07185813,  1.74670943],
       [-0.61879834,  0.17593425, -0.85653356, -2.13051604],
       [-0.25101262,  0.3972118 ,  0.79066474,  0.36282782]])

In [ ]:
e1=np.random.randint(low=10,high=20,size=(3,3))
e1

array([[10, 10, 16],
       [13, 18, 11],
       [14, 19, 15]])

In [ ]:
m=np.mean(e1)
print(m)

14.0


create 2d array of 4*4 using random integer,change its shape into 2 diff array

In [ ]:
e1=np.random.randn(1,2,3,4)
e1


array([[[[-1.83283412,  0.98304266,  1.11661828,  0.72520725],
         [ 0.14258071,  0.20424361,  1.05741739,  1.33172908],
         [ 0.19238618,  1.93423404,  1.63228475, -1.26478215]],

        [[-0.43892896, -0.78665163, -1.26723955,  0.01265005],
         [ 0.85056939,  0.58174988,  0.21321635, -1.16650568],
         [-0.1735852 ,  1.07029831, -0.93859136, -1.08157905]]]])

In [ ]:
e1.shape

(1, 2, 3, 4)

In [ ]:
e1.reshape(1,2,3,4)

array([[[[-1.83283412,  0.98304266,  1.11661828,  0.72520725],
         [ 0.14258071,  0.20424361,  1.05741739,  1.33172908],
         [ 0.19238618,  1.93423404,  1.63228475, -1.26478215]],

        [[-0.43892896, -0.78665163, -1.26723955,  0.01265005],
         [ 0.85056939,  0.58174988,  0.21321635, -1.16650568],
         [-0.1735852 ,  1.07029831, -0.93859136, -1.08157905]]]])

In [ ]:
e1

array([[[[-1.83283412,  0.98304266,  1.11661828,  0.72520725],
         [ 0.14258071,  0.20424361,  1.05741739,  1.33172908],
         [ 0.19238618,  1.93423404,  1.63228475, -1.26478215]],

        [[-0.43892896, -0.78665163, -1.26723955,  0.01265005],
         [ 0.85056939,  0.58174988,  0.21321635, -1.16650568],
         [-0.1735852 ,  1.07029831, -0.93859136, -1.08157905]]]])

In [ ]:
a=np.full((2,2),4)
a

array([[4, 4],
       [4, 4]])

In [ ]:
b=np.full((10,10),8)
b

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [ ]:
c=np.full((6,6),8,dtype='float')
c

array([[8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8.]])

In [ ]:
d=np.eye(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
g=np.append(a,[5,6,7,8,9,10])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
c=np.array([[2,3,4],[8,9,0]])
c

array([[2, 3, 4],
       [8, 9, 0]])

In [ ]:
np.shape(c)

(2, 3)

In [ ]:
np.append(c,[[4,5,6]],axis=0)

array([[2, 3, 4],
       [8, 9, 0],
       [4, 5, 6]])

In [ ]:
c=np.append(c,[[11,22,33]],axis=0)
c

array([[ 2,  3,  4],
       [ 8,  9,  0],
       [11, 22, 33]])

In [ ]:
b

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
c.size

9

In [ ]:
#c.reshape(6,2)

In [ ]:
h=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9])
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
h=np.append(h,[8,9,1,3])
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 1, 3])

In [ ]:
h.size

14

In [ ]:
np.shape(h)

(14,)

In [ ]:
#h.reshape(2,9)

In [ ]:
k=np.array([5,6,7,3,9,11,21])
k

array([ 5,  6,  7,  3,  9, 11, 21])

In [ ]:
n=np.delete(k,[2,5])
n

array([ 5,  6,  3,  9, 21])

In [ ]:
n=np.array([[11,12,13],[44,55,66],[77,88,99]])
n

array([[11, 12, 13],
       [44, 55, 66],
       [77, 88, 99]])

In [ ]:
n=np.delete(n,1,axis=0)
n

array([[11, 12, 13],
       [77, 88, 99]])

In [ ]:
n=np.delete(n,0,axis=1)
n

array([[12, 13],
       [88, 99]])

In [ ]:
arr1 = np.arange(9)

In [ ]:
arr1.size

9

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr1=arr1.reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr1*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
arr1**3

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]])

In [ ]:
a1=np.random.randint(1,10,size=(3,3))
a1

array([[3, 4, 1],
       [7, 9, 2],
       [8, 4, 1]])

In [ ]:
b1=np.random.randint(1,10,size=(3,3))
b1

array([[3, 8, 5],
       [1, 4, 8],
       [6, 4, 8]])

In [ ]:
print(a1)
print(b1)

[[3 4 1]
 [7 9 2]
 [8 4 1]]
[[3 8 5]
 [1 4 8]
 [6 4 8]]


In [ ]:
c1=a1+b1
print(c1)

[[ 6 12  6]
 [ 8 13 10]
 [14  8  9]]


In [ ]:
c1=a1-b1
print(c1)

[[ 0 -4 -4]
 [ 6  5 -6]
 [ 2  0 -7]]


In [ ]:
print(a1+b1)
print(a1-b1)
print(a1*b1)
print(a1/b1)

[[ 6 12  6]
 [ 8 13 10]
 [14  8  9]]
[[ 0 -4 -4]
 [ 6  5 -6]
 [ 2  0 -7]]
[[ 9 32  5]
 [ 7 36 16]
 [48 16  8]]
[[1.         0.5        0.2       ]
 [7.         2.25       0.25      ]
 [1.33333333 1.         0.125     ]]


In [ ]:
a1

array([[3, 4, 1],
       [7, 9, 2],
       [8, 4, 1]])

In [ ]:
d1=np.array([1,2,3,4,5])

In [ ]:
np.repeat(d1,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [ ]:
np.tile(c1,4)

array([[ 0, -4, -4,  0, -4, -4,  0, -4, -4,  0, -4, -4],
       [ 6,  5, -6,  6,  5, -6,  6,  5, -6,  6,  5, -6],
       [ 2,  0, -7,  2,  0, -7,  2,  0, -7,  2,  0, -7]])

In [ ]:
f1=np.array([[1,2,3],[4,5,6]])
f1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.repeat(f1,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [ ]:
np.tile(f1,2)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

create 2 matriex nxm from 1D array using reshape find (A1*2/B1*4)^3

In [ ]:
A1=np.arange(1,10)
A1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
B1=np.arange(1,10)
B1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
A1=A1.reshape(3,-1)
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B1=B1.reshape(3,-1)
B1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A1=A1*2
A1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
B1=B1*4
B1

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [ ]:
Z1=A1/B1
Z1

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [ ]:
Z1**3

array([[0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125]])

In [ ]:
Z1>0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
A1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
A1>3

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.sqrt(A1)

array([[1.41421356, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162],
       [3.74165739, 4.        , 4.24264069]])

In [ ]:
A1.sum()

np.int64(90)

In [ ]:
A1.mean()

np.float64(10.0)

In [ ]:
arr1=np.array([[1,2,5,6,7]])
arr1

array([[1, 2, 5, 6, 7]])

In [ ]:
arr_mean=arr1.mean()

In [ ]:
arr_mean

np.float64(4.2)

In [ ]:
arr1=np.array([[1,2,5],[8,6,7]])
arr1

array([[1, 2, 5],
       [8, 6, 7]])

In [ ]:
arr1.sum(axis=0)
arr1

array([[1, 2, 5],
       [8, 6, 7]])

In [ ]:
arr1.sum(axis=1)
arr1

array([[1, 2, 5],
       [8, 6, 7]])

In [ ]:
A1=np.array([[2,3,4],[8,9,0]])
A1

array([[2, 3, 4],
       [8, 9, 0]])

In [ ]:
A1_mean=A1-A1.mean()
A1_mean

array([[-2.33333333, -1.33333333, -0.33333333],
       [ 3.66666667,  4.66666667, -4.33333333]])

In [ ]:
A1.sum(axis=0)
A1.sum()

np.int64(26)

In [ ]:
A1.sum(axis=1)
A1.sum()

np.int64(26)

In [ ]:
while True:
  num=np.random.randint(1,11)
  print(num)
  if(num==10):
    break

1
3
1
7
6
8
3
2
8
2
7
2
10


In [ ]:
A = np.arange(36).reshape(6, 6)
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
B = np.arange(36).reshape(6, 6)
print(B)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
C = np.arange(36).reshape(6, 6)
print(C)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
A**4

array([[      0,       1,      16,      81,     256,     625],
       [   1296,    2401,    4096,    6561,   10000,   14641],
       [  20736,   28561,   38416,   50625,   65536,   83521],
       [ 104976,  130321,  160000,  194481,  234256,  279841],
       [ 331776,  390625,  456976,  531441,  614656,  707281],
       [ 810000,  923521, 1048576, 1185921, 1336336, 1500625]])

In [ ]:
B+C

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70]])

In [ ]:
D=(A**4)*(B+C)
print(D)

[[        0         2        64       486      2048      6250]
 [    15552     33614     65536    118098    200000    322102]
 [   497664    742586   1075648   1518750   2097152   2839714]
 [  3779136   4952198   6400000   8168202  10307264  12872686]
 [ 15925248  19531250  23762752  28697814  34420736  41022298]
 [ 48600000  57258302  67108864  78270786  90870848 105043750]]


In [ ]:
A.sum()

np.int64(630)

In [ ]:
B.sum()

np.int64(630)

In [ ]:
C.sum()

np.int64(630)

In [ ]:
A.mean()

np.float64(17.5)

In [ ]:
B.mean()

np.float64(17.5)

In [ ]:
C.mean()

np.float64(17.5)

In [ ]:
A.sum(axis=0)
A.sum()

np.int64(630)

In [ ]:
B.sum(axis=0)
B.sum()

np.int64(630)

In [ ]:
C.sum(axis=0)
C.sum()

np.int64(630)

In [ ]:
A.sum(axis=1)
A.sum()

np.int64(630)

In [ ]:
B.sum(axis=1)
B.sum()

np.int64(630)

In [ ]:
C.sum(axis=1)
C.sum()

np.int64(630)

In [ ]:
min_rows = B.min(axis=1)
print("Minimum value of each row:")
print(min_rows)
max_rows = B.max(axis=1)
print("\nMaximum value of each row:")
print(max_rows)
min_cols = B.min(axis=0)
print("\nMinimum value of each column:")
print(min_cols)
max_cols = B.max(axis=0)
print("\nMaximum value of each column:")
print(max_cols)

Minimum value of each row:
[ 0  6 12 18 24 30]

Maximum value of each row:
[ 5 11 17 23 29 35]

Minimum value of each column:
[0 1 2 3 4 5]

Maximum value of each column:
[30 31 32 33 34 35]


In [ ]:
min_rows = A.min(axis=1)
print("Minimum value of each row:")
print(min_rows)
max_rows = A.max(axis=1)
print("\nMaximum value of each row:")
print(max_rows)
min_cols = A.min(axis=0)
print("\nMinimum value of each column:")
print(min_cols)
max_cols = A.max(axis=0)
print("\nMaximum value of each column:")
print(max_cols)

Minimum value of each row:
[ 0  6 12 18 24 30]

Maximum value of each row:
[ 5 11 17 23 29 35]

Minimum value of each column:
[0 1 2 3 4 5]

Maximum value of each column:
[30 31 32 33 34 35]


In [ ]:
min_rows = C.min(axis=1)
print("Minimum value of each row:")
print(min_rows)
max_rows = C.max(axis=1)
print("\nMaximum value of each row:")
print(max_rows)
min_cols = C.min(axis=0)
print("\nMinimum value of each column:")
print(min_cols)
max_cols = C.max(axis=0)
print("\nMaximum value of each column:")
print(max_cols)

Minimum value of each row:
[ 0  6 12 18 24 30]

Maximum value of each row:
[ 5 11 17 23 29 35]

Minimum value of each column:
[0 1 2 3 4 5]

Maximum value of each column:
[30 31 32 33 34 35]


In [ ]:
a=13.23456
np.round(a,3)

np.float64(13.235)

In [ ]:
arr1=np.random.randint(1,10,9)
arr1

array([1, 9, 9, 5, 4, 2, 2, 1, 8])

In [ ]:
arr1=(arr1*13.23456).astype(float)
arr1

array([ 13.23456, 119.11104, 119.11104,  66.1728 ,  52.93824,  26.46912,
        26.46912,  13.23456, 105.87648])

In [ ]:
arr1=np.round(arr1,2)
arr1

array([ 13.23, 119.11, 119.11,  66.17,  52.94,  26.47,  26.47,  13.23,
       105.88])

In [ ]:
a

13.23456

In [ ]:
np.ceil(a)

np.float64(14.0)

In [ ]:
np.floor(a)

np.float64(13.0)

In [ ]:
arr1=np.random.randint(1,10,9)
arr1

array([1, 1, 8, 8, 5, 3, 2, 4, 6])

In [ ]:
arr1.size

9

In [ ]:
arr1.reshape(3,3)

array([[1, 1, 8],
       [8, 5, 3],
       [2, 4, 6]])

In [ ]:
D=arr1*3.14256789
D

array([ 3.14256789,  3.14256789, 25.14054312, 25.14054312, 15.71283945,
        9.42770367,  6.28513578, 12.57027156, 18.85540734])

In [ ]:
D

array([ 3.14256789,  3.14256789, 25.14054312, 25.14054312, 15.71283945,
        9.42770367,  6.28513578, 12.57027156, 18.85540734])

In [ ]:
np.ceil(arr1)

array([1., 1., 8., 8., 5., 3., 2., 4., 6.])

In [ ]:
arr1=np.round(arr1,2)
arr1

array([1, 1, 8, 8, 5, 3, 2, 4, 6])

In [ ]:
np.floor(arr1)

array([1., 1., 8., 8., 5., 3., 2., 4., 6.])

In [ ]:
arr1

array([1, 1, 8, 8, 5, 3, 2, 4, 6])

In [ ]:
arr1.argmax()

np.int64(2)

In [ ]:
arr1.argmin()

np.int64(0)

In [ ]:
A=np.random.randint(1,5,6).reshape(2,3)
A

array([[4, 4, 1],
       [3, 1, 4]])

In [ ]:
B=np.random.randint(1,5,6).reshape(3,2)
B

array([[4, 2],
       [3, 1],
       [4, 1]])

In [ ]:
np.shape(B)

(3, 2)

In [ ]:
C=np.dot(A,B)
C

array([[32, 13],
       [31, 11]])

In [ ]:
C

array([[32, 13],
       [31, 11]])

In [ ]:
np.transpose(C)

array([[32, 31],
       [13, 11]])

In [ ]:
np.linalg.inv(C)

array([[-0.21568627,  0.25490196],
       [ 0.60784314, -0.62745098]])

In [ ]:
np.linalg.det(C)

np.float64(-51.0)

In [ ]:
A=np.random.randint(2,3,18).reshape(3,6)
A

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [ ]:
B=np.random.randint(2,3,18).reshape(6,3)
B

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.shape(B)

(6, 3)

In [ ]:
C=np.dot(A,B)
C

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]])

In [ ]:
np.transpose(C)

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]])

In [ ]:
#np.linalg.inv(C)

In [ ]:
arr1

array([1, 1, 8, 8, 5, 3, 2, 4, 6])

In [ ]:
np.size(arr1)

9

In [ ]:
arr1.reshape(3,3)

array([[1, 1, 8],
       [8, 5, 3],
       [2, 4, 6]])

In [ ]:
arr1[2]


np.int64(8)

In [ ]:
arr1[6]

np.int64(2)

In [ ]:
arr1[8]

np.int64(6)

In [ ]:
F=np.array([[[1,2,0],[1,3,4],[4,5,6],[9,7,8]]])
F

array([[[1, 2, 0],
        [1, 3, 4],
        [4, 5, 6],
        [9, 7, 8]]])

In [ ]:
F

array([[[1, 2, 0],
        [1, 3, 4],
        [4, 5, 6],
        [9, 7, 8]]])

In [ ]:
F.shape

(1, 4, 3)

In [ ]:
F[[0,0,0],F[0,0,1],F[0,1,0]]

array([5, 5, 5])

In [ ]:
R=np.array([[1,2,3],[4,5,6],[7,8,9]]).reshape(3,3)
R

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
R[[1,1],[0,2]]

array([4, 6])

In [ ]:
R[[0,0,2,2],[0,2,0,2]]

array([1, 3, 7, 9])

In [ ]:
b1=np.arange(1,10)
b1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b1[2:8]

array([3, 4, 5, 6, 7, 8])

In [ ]:
b1[-1:-6]

array([], dtype=int64)

In [ ]:
c1=np.arange(1,10)
c1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
c1[3:9]

array([4, 5, 6, 7, 8, 9])

In [ ]:
c1[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
c1[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
c1[-3:-9]

array([], dtype=int64)

In [ ]:
c1[-1:]

array([9])

In [ ]:
c1[:-7]

array([1, 2])

In [ ]:
c1=np.arange(1,10).reshape(3,3)
c1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
c1[:3,:1]
c1[:3,2:]
c1[:3,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
c1[:1],c1[:2],c1[:3]

(array([[1, 2, 3]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [ ]:
K=np.arange(1,10).reshape(3,3)
K

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
L=np.array([[2,3,4],[5,6,7],[8,9,10]])
L

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
M=np.dot(K,L)
M

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [ ]:
N=M[[0,0,1,1],
    [0,1,0,1]]

In [ ]:
N.reshape(2,2)

array([[36, 42],
       [81, 96]])

In [ ]:
O=M[[0,0,1,1],[1,2,1,2]]

In [ ]:
O.reshape(2,2)

array([[ 42,  48],
       [ 96, 111]])

In [ ]:
J=N+O
J.reshape(2,2)

array([[ 78,  90],
       [177, 207]])

In [ ]:
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
X[1:2,0:]

array([[4, 5, 6]])

# Task
Here's the first step:

**Read and Display 1D Array Elements**: Write a Python program using NumPy to create a 1D array and then display its elements.

```python
# Create a 1D array
one_d_array = np.array([10, 20, 30, 40, 50])

# Display its elements
print("1D Array Elements:", one_d_array)
```

## Read and Display 1D Array Elements

### Subtask:
Write a Python program using NumPy to create a 1D array and then display its elements.


**Reasoning**:
The subtask requires creating a 1D NumPy array with specific elements and then displaying them. I will use `np.array()` to create the array and then `print()` to display its content, directly addressing both instructions.



In [ ]:
import numpy as np

one_d_array = np.array([10, 20, 30, 40, 50])
print(one_d_array)

[10 20 30 40 50]


## Find Largest and Smallest Element

### Subtask:
Write a Python program using NumPy to find and print the largest and smallest elements within an array.


**Reasoning**:
The subtask requires finding the largest and smallest elements in a NumPy array. I will create a NumPy array, then use `np.max()` and `np.min()` to find these values, and finally print them as instructed.



In [ ]:
my_array = np.array([15, 27, 8, 42, 3, 50, 11])

largest_element = np.max(my_array)
smallest_element = np.min(my_array)

print("Original Array:", my_array)
print("Largest Element:", largest_element)
print("Smallest Element:", smallest_element)

Original Array: [15 27  8 42  3 50 11]
Largest Element: 50
Smallest Element: 3


## Calculate Sum and Average

### Subtask:
Write a Python program using NumPy to calculate and display the sum and average of all elements in an array.


**Reasoning**:
The subtask requires creating a NumPy array, then calculating and displaying its sum and average. I will use the `my_array` from a previous step, and then use `np.sum()` and `np.mean()` functions to calculate the sum and average respectively. Finally, I will print all the required information with proper labels.

**Reasoning**:
Implement the code to calculate the sum and average of the elements in `my_array` and display the results as specified in the instructions.



In [ ]:
my_array = np.array([15, 27, 8, 42, 3, 50, 11])

array_sum = np.sum(my_array)
array_average = np.mean(my_array)

print("Original Array:", my_array)
print("Sum of Array Elements:", array_sum)
print("Average of Array Elements:", array_average)

Original Array: [15 27  8 42  3 50 11]
Sum of Array Elements: 156
Average of Array Elements: 22.285714285714285


## Count Positive, Negative, and Zero Elements

### Subtask:
Write a Python program using NumPy to count and display the number of positive, negative, and zero elements present in an array.


## Count Positive, Negative, and Zero Elements

### Subtask:
Write a Python program using NumPy to count and display the number of positive, negative, and zero elements present in an array.


**Reasoning**:
The subtask requires counting positive, negative, and zero elements in a NumPy array. I will use boolean indexing and the `sum()` method to efficiently count these categories and then display the results with clear labels.



In [ ]:
import numpy as np

# 1. Create a NumPy array with mixed values
my_array = np.array([-5, 0, 10, -2, 7, 0, 1, 15, -8, 0])

# 2. Count positive elements
positive_count = (my_array > 0).sum()

# 3. Count negative elements
negative_count = (my_array < 0).sum()

# 4. Count zero elements
zero_count = (my_array == 0).sum()

# 5. Print the results
print("Original Array:", my_array)
print("Number of Positive Elements:", positive_count)
print("Number of Negative Elements:", negative_count)
print("Number of Zero Elements:", zero_count)

Original Array: [-5  0 10 -2  7  0  1 15 -8  0]
Number of Positive Elements: 4
Number of Negative Elements: 3
Number of Zero Elements: 3


## Copy One Array to Another

### Subtask:
Write a Python program using NumPy to create an array and then copy its contents to a new array.


**Reasoning**:
The subtask requires creating a 1D array, making a deep copy using `np.copy()`, and then printing both arrays to verify the copy. This code block will directly implement these steps.



In [ ]:
import numpy as np

# 1. Create a 1D NumPy array
original_array = np.array([10, 20, 30, 40, 50])

# 2. Create a new array by making a deep copy of original_array
copied_array = np.copy(original_array)

# 3. Print both arrays to verify the copy
print("Original Array:", original_array)
print("Copied Array:", copied_array)

Original Array: [10 20 30 40 50]
Copied Array: [10 20 30 40 50]


## Bubble Sort Algorithm

### Subtask:
Implement the bubble sort algorithm in Python to sort the elements of an array.


**Reasoning**:
The subtask requires implementing the bubble sort algorithm to sort a NumPy array. I will define the `bubble_sort` function, apply the sorting logic with nested loops and swapping, create an example array, call the function, and then print the original and sorted arrays to demonstrate the result.



In [ ]:
import numpy as np

def bubble_sort(arr):
    n = len(arr)
    for i in range(n - 1):
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr

# Create an example NumPy array
example_array = np.array([64, 34, 25, 12, 22, 11, 90])

# Make a copy to preserve the original for printing
original_array = np.copy(example_array)

# Call the bubble_sort function
sorted_array = bubble_sort(example_array)

# Print the original and sorted arrays
print("Original Array:", original_array)
print("Sorted Array (using Bubble Sort):", sorted_array)

Original Array: [64 34 25 12 22 11 90]
Sorted Array (using Bubble Sort): [11 12 22 25 34 64 90]


# Task
## Merge Two Arrays Implementation

### Subtask:
Create two example 1D NumPy arrays and use `np.concatenate()` to merge them into a single new array. Then, print all three arrays to verify the merging operation.

## Merge Two Arrays Implementation

### Subtask:
Create two example 1D NumPy arrays and use `np.concatenate()` to merge them into a single new array. Then, print all three arrays to verify the merging operation.


**Reasoning**:
To merge two 1D NumPy arrays, I will first define two example arrays. Then, I will use the `np.concatenate()` function to combine them into a single array. Finally, I will print all three arrays (the two original ones and the merged one) to confirm that the operation was successful and as expected.

**Reasoning**:
I will create two 1D NumPy arrays, concatenate them using `np.concatenate()`, and then print all three arrays (the two original and the merged one) to fulfill the subtask requirements.



In [ ]:
import numpy as np

# 1. Create two 1D NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# 2. Use np.concatenate() to merge array1 and array2
merged_array = np.concatenate((array1, array2))

# 3. Print array1, array2, and merged_array
print("Array 1:", array1)
print("Array 2:", array2)
print("Merged Array:", merged_array)

Array 1: [1 2 3]
Array 2: [4 5 6]
Merged Array: [1 2 3 4 5 6]


## Final Task

### Subtask:
Consolidate and present all the solutions for the array manipulation assignments.


## Summary:

### Data Analysis Key Findings
*   Two 1D NumPy arrays, `[1 2 3]` and `[4 5 6]`, were successfully merged using `np.concatenate()`.
*   The merging operation resulted in a new array `[1 2 3 4 5 6]`, confirming that the elements of the first array were followed by the elements of the second array.

### Insights or Next Steps
*   This method is effective for straightforward 1D array concatenation.
*   Explore how `np.concatenate()` handles arrays with different dimensions or axes, and consider using `np.vstack()` or `np.hstack()` for specific stacking operations.
