<a href="https://colab.research.google.com/github/Manju1803-a11y/NA_assignment/blob/main/Numpy_array_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

create a  1d array of 20 elements with a value diff is 4
1)convert in 2d array and print it
2)convert it into 3d array and print it
3)convert 2d into 1d and append 11,22,33 into it
4)in the 1d, delete the values from index 4 to 8
5)convert the resulting array into 2d(subjected to add elements)
6)append two rows and 2 columns into the matrix
7)delete the row or column requested by the user

In [ ]:
import numpy as np


In [ ]:
m = np.arange(0, 4 * 20, 4)
print(m)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76]


In [ ]:
np.shape(m)

(20,)

In [ ]:
m.reshape(5,4)

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44],
       [48, 52, 56, 60],
       [64, 68, 72, 76]])

In [ ]:
m.reshape(20,1,1)

array([[[ 0]],

       [[ 4]],

       [[ 8]],

       [[12]],

       [[16]],

       [[20]],

       [[24]],

       [[28]],

       [[32]],

       [[36]],

       [[40]],

       [[44]],

       [[48]],

       [[52]],

       [[56]],

       [[60]],

       [[64]],

       [[68]],

       [[72]],

       [[76]]])

In [ ]:
m.reshape(5,4)

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44],
       [48, 52, 56, 60],
       [64, 68, 72, 76]])

In [ ]:
m.reshape(20,)
#m=np.append(m,[11,22,33])

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76])

In [ ]:
m=np.array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76])
m

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76])

In [ ]:
m=np.append(m,[11,22,33])
m

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 11, 22, 33])

In [ ]:
m=np.delete(m,[4,8])
m

array([ 0,  4,  8, 12, 20, 24, 28, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72,
       76, 11, 22, 33])

In [ ]:

np.shape(m)

(21,)

In [ ]:
m.ndim

1

In [ ]:
np.reshape(11,1)

array([11])

In [ ]:
np.append(m,[22],axis=0)

array([ 0,  4,  8, 12, 20, 24, 28, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72,
       76, 11, 22, 33, 22])

In [ ]:
m.ndim

1

In [ ]:
m.shape

(21,)

In [ ]:
m=np.delete(m,[2])
m

array([ 0,  4, 12, 20, 24, 28, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76,
       11, 22, 33])

In [ ]:
m.ndim

1

In [ ]:
m.shape

(20,)

In [ ]:
m.reshape(9,2)

ValueError: cannot reshape array of size 20 into shape (9,2)

In [ ]:
np.append(m,[[1,2]],axis=0)

Design a python program for the following output (add viwing option for the array) welcome to numpy arrays
1. create 1D array 2.create 2D array 3.convert 1Dto2D 4.Convert 2D to 1D

In [ ]:
import numpy as np
print("Welcome to NumPy Arrays")
array = None
def create_1d_array():
    global array
    elements = input("Enter elements for 1D array separated by space (e.g., 1 2 3 4): ")
    elements = elements.strip().replace('[', '').replace(']', '')
    try:
        array = np.array([int(x) for x in elements.split()])
        print("1D Array Created:\n", array)
    except ValueError:
        print("Invalid input. Please enter integers separated by spaces.")
def create_2d_array():
    global array
    try:
        rows = int(input("Enter number of rows: "))
        elements_str = input(f"Enter elements for {rows} rows separated by space (e.g., 1 2 3 4 5 6):\n")
        flat_list = [int(x) for x in elements_str.split()]
        if len(flat_list) % rows == 0:
            cols = len(flat_list) // rows
            array = np.array(flat_list).reshape(rows, cols)
            print("2D Array Created:\n", array)
        else:
            print(f"Invalid input: Number of elements ({len(flat_list)}) is not divisible by the number of rows ({rows}).")
    except ValueError:
        print("Invalid input. Please enter integers separated by spaces for elements and a valid integer for the number of rows.")
def convert_1d_to_2d():
    global array
    if array is not None and array.ndim == 1:
        try:
            cols = int(input("Enter number of columns for 2D conversion: "))
            if len(array) % cols == 0:
                array = array.reshape(-1, cols)
                print("Converted to 2D:\n", array)
            else:
                print("Cannot reshape: Elements not divisible by columns.")
        except ValueError:
            print("Invalid input for number of columns.")
    else:
        print("Current array is not 1D or doesn't exist.")
def convert_2d_to_1d():
    global array
    if array is not None and array.ndim == 2:
        array = array.flatten()
        print("Converted to 1D:\n", array)
    else:
        print("Current array is not 2D or doesn't exist.")
def view_array():
    global array
    if array is not None:
        print("Current Array:\n", array)
    else:
        print("No array available.")
while True:
    print("\nMenu:\n1. Create 1D array\n2. Create 2D array\n3. Convert 1D to 2D\n4. Convert 2D to 1D\n5. View array\n6. Exit")
    choice = input("Enter your choice: ")
    if choice == '1':
        create_1d_array()
    elif choice == '2':
        create_2d_array()
    elif choice == '3':
        convert_1d_to_2d()
    elif choice == '4':
        convert_2d_to_1d()
    elif choice == '5':
        view_array()
    elif choice == '6':
        print("Exiting program.")
        break
    else:
        print("Invalid choice. Please try again.")

Welcome to NumPy Arrays

Menu:
1. Create 1D array
2. Create 2D array
3. Convert 1D to 2D
4. Convert 2D to 1D
5. View array
6. Exit
Enter your choice: 6
Exiting program.


In [ ]:
import numpy as np

array = None

def create_1d_array():
    global array
    arr_input = input("Enter elements separated by space: ")
    arr_list = list(map(int, arr_input.split()))
    array = np.array(arr_list)
    print("1D array created.")

def create_2d_array():
    global array
    rows = int(input("Enter number of rows: "))
    cols = int(input("Enter number of columns: "))
    print(f"Enter {rows*cols} elements separated by space:")
    elements = list(map(int, input().split()))
    if len(elements) != rows * cols:
        print("Number of elements doesn't match shape.")
        return
    array = np.array(elements).reshape(rows, cols)
    print("2D array created.")

def convert_1d_to_2d():
    global array
    if array is None:
        print("No array available.")
        return
    if len(array.shape) != 1:
        print("Current array is not 1D.")
        return
    rows = int(input("Enter number of rows for 2D array: "))
    if array.size % rows != 0:
        print("Cannot reshape array with given rows.")
        return
    array = array.reshape(rows, array.size // rows)
    print("Array converted to 2D.")

def convert_2d_to_1d():
    global array
    if array is None:
        print("No array available.")
        return
    if len(array.shape) != 2:
        print("Current array is not 2D.")
        return
    array = array.flatten()
    print("Array converted to 1D.")

def view_array():
    global array
    if array is not None:
        print("Current Array:\n", array)
    else:
        print("No array available.")

def arithmetic_operations():
    global array
    if array is None:
        print("No array available to perform operations.")
        return

    print("Choose operation:")
    print("1. Add scalar")
    print("2. Subtract scalar")
    print("3. Multiply by scalar")
    print("4. Divide by scalar")
    print("5. Add another array")
    print("6. Subtract another array")
    print("7. Multiply by another array (element-wise)")

    op = input("Enter your choice: ")

    if op in ['1', '2', '3', '4']:
        try:
            scalar = float(input("Enter scalar value: "))
        except ValueError:
            print("Invalid scalar.")
            return

        if op == '1':
            array = array + scalar
        elif op == '2':
            array = array - scalar
        elif op == '3':
            array = array * scalar
        elif op == '4':
            if scalar == 0:
                print("Division by zero is not allowed.")
                return
            array = array / scalar
        print("Operation performed successfully.")

    elif op in ['5', '6', '7']:
        print("Enter elements of the second array separated by space:")
        elements = list(map(float, input().split()))
        other = np.array(elements)

        # For operations on arrays, shapes must be compatible
        try:
            if op == '5':
                result = array + other
            elif op == '6':
                result = array - other
            elif op == '7':
                result = array * other
        except ValueError:
            print("Arrays have incompatible shapes for this operation.")
            return

        array = result
        print("Operation performed successfully.")
    else:
        print("Invalid choice.")

def resize_array():
    global array
    if array is None:
        print("No array available to resize.")
        return
    print(f"Current array shape: {array.shape}")
    try:
        if len(array.shape) == 1:
            new_size = int(input("Enter new size for 1D array: "))
            if new_size <= 0:
                print("Invalid size.")
                return
            # Resize (if larger, fill with zeros; if smaller, truncate)
            new_array = np.zeros(new_size, dtype=array.dtype)
            min_len = min(new_size, array.size)
            new_array[:min_len] = array[:min_len]
            array = new_array
        elif len(array.shape) == 2:
            rows = int(input("Enter new number of rows: "))
            cols = int(input("Enter new number of columns: "))
            if rows <= 0 or cols <= 0:
                print("Invalid size.")
                return
            new_size = rows * cols
            flat = array.flatten()
            new_array = np.zeros(new_size, dtype=array.dtype)
            min_len = min(new_size, flat.size)
            new_array[:min_len] = flat[:min_len]
            array = new_array.reshape(rows, cols)
        else:
            print("Resize not supported for arrays with more than 2 dimensions.")
            return
        print("Array resized successfully.")
    except Exception as e:
        print("Error resizing array:", e)


while True:
    print("\nMenu:")
    print("1. Create 1D array")
    print("2. Create 2D array")
    print("3. Convert 1D to 2D")
    print("4. Convert 2D to 1D")
    print("5. View array")
    print("6. Perform arithmetic operations")
    print("7. Resize array")
    print("8. Exit")

    choice = input("Enter your choice: ")
    if choice == '1':
        create_1d_array()
    elif choice == '2':
        create_2d_array()
    elif choice == '3':
        convert_1d_to_2d()
    elif choice == '4':
        convert_2d_to_1d()
    elif choice == '5':
        view_array()
    elif choice == '6':
        arithmetic_operations()
    elif choice == '7':
        resize_array()
    elif choice == '8':
        print("Exiting program.")
        break
    else:
        print("Invalid choice. Please try again.")


Menu:
1. Create 1D array
2. Create 2D array
3. Convert 1D to 2D
4. Convert 2D to 1D
5. View array
6. Perform arithmetic operations
7. Resize array
8. Exit
Enter your choice: 8
Exiting program.


In [ ]:
G=np.random.randint(1,10,9).reshape(3,3)
G

array([[7, 5, 6],
       [3, 6, 3],
       [5, 3, 4]])

In [ ]:
H=np.random.randint(1,12,9).reshape(3,3)
H

array([[ 5, 11,  2],
       [ 9,  2,  9],
       [ 8,  1,  8]])

In [ ]:
np.shape(H)

(3, 3)

In [ ]:
I=np.dot(G,H)
I

array([[128,  93, 107],
       [ 93,  48,  84],
       [ 84,  65,  69]])

In [ ]:
I[I%2==0]

array([128,  48,  84,  84])

In [ ]:
I.ndim

2