<a href="https://colab.research.google.com/github/Manju1803-a11y/NA_assignment/blob/main/NumpyA1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
A=np.arange(1,9)
A

array([1, 2, 3, 4, 5, 6, 7, 8])

create 3x3 Numpy array filled with all zeros

In [ ]:
b=np.full((3,3),0)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Generate an array of even number between 10 and 30

In [ ]:
c=np.arange(10,30)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [ ]:
even_numbers = c[c % 2 == 0]
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28]


To print the first and last element using slicing

In [ ]:
arr=np.array([10,20,30,40,50])
arr[:1]
#arr[]

array([10])

create 5x5 identity matrix using numpy

In [ ]:
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

a=np.arange(1,10),reshape into 3x3 matrix.

In [ ]:
a=np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

find the sum and mean of given elements

In [ ]:
a=np.array([2,4,6,8,10])
a

array([ 2,  4,  6,  8, 10])

In [ ]:
a.sum()

np.int64(30)

In [ ]:
a.mean()

np.float64(6.0)

find the index value of 15

In [ ]:
a=np.array([5,10,15,20,25])
a

array([ 5, 10, 15, 20, 25])

In [ ]:
index = np.where(a == 15)
print(index)

(array([2]),)
